config/routes.rb
Rails.application.routes.draw do

  resources :books
  resources :categories
  resources :authors
  resources :publishers

  get 'about' => 'about#index'
  get '/hello' , :to => redirect('/helloworld.html')
  root 'books#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :category
  belongs_to :author
  belongs_to :publisher
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books

  validates :name, presence: true, length:{minimum:3}
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :books
  
  validates :name, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @page_title = 'About Us'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
  end

  def new
    @page_title = 'Add New Author'
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to authors_path
      flash[:notice] = 'Author Created!'
    else
      render :new
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    @author.update(author_params)
    flash[:notice] = "Updated Success!"
    redirect_to authors_path
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    flash[:alert] = "Author Removed"
    redirect_to authors_path
  end


  private

  def author_params
    params.require(:author).permit(:first_name, :last_name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  end

  def show
  end

  def new
    @book = Book.new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @page_title = 'Add New Category'
    @category = Category.new
    #因為這邊category是給所有的讀者共用的，
    #所以不需要使用somebody.categories.new這種方式增加
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    flash[:notice] = "Category Updated"
    
    redirect_to categories_path
  end

  def destroy
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/about/index.html.erb
<h1><%= @page_title %></h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ut rutrum felis, in egestas lacus. Sed convallis sagittis ligula, ac mollis dui posuere vitae. Sed id neque ornare, fermentum mauris pharetra, hendrerit sapien. Curabitur aliquam risus ipsum, vel bibendum ex luctus sagittis. Mauris elementum suscipit ante et egestas. Praesent sed leo elementum, faucibus est quis, euismod nunc. Duis pulvinar nisi non odio volutpat efficitur. Cras leo massa, ornare eu commodo mattis, placerat iaculis risus. Donec sed ligula sed felis elementum imperdiet a sit amet urna. Aliquam tempor, ex non luctus efficitur, augue sapien consequat ante, ut molestie dolor risus nec erat. Suspendisse faucibus odio vel felis vestibulum, ut bibendum dui sollicitudin. Integer dictum magna dui. Sed in libero iaculis, gravida augue et, consequat sem. Integer euismod semper ligula, at convallis ligula congue ullamcorper. Aenean at mollis quam, ut ornare enim.</p>

app/views/authors/edit.html.erb
<h2><%= @page_title %></h2>

<%= form_for @author do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name , class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name , class: 'form-control' %>
  </div>

  <%= f.submit "Submit", class: "btn btn-primary" %>
  <%= link_to "Cancel", authors_path, class: "btn btn-default" %>

<% end %>

app/views/authors/index.html.erb
<h2>Authors</h2>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @authors.each do |author| %>
    <tr>
      <td><%= author.first_name %></td>
      <td><%= author.last_name %></td>
      <td>
        <%= link_to "Edit", edit_author_path(author) %>
        <%= link_to "Delete", author_path(author), method: :delete, data: { confirm: "Are you sure?" } %>  
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/authors/new.html.erb
<h2><%= @page_title %></h2>

<form action="<%= authors_path %>" method="post">
  <div class="form-group">
    <label for="first-name">First Name:</label>
    <input type="text" class="form-control" id="first-name" name="author[first_name]" placeholder="">
  </div>

  <div class="form-group">
    <label for="last-name">Last Name:</label>
    <input type="text" class="form-control" id="last-name" name="author[last_name]" placeholder="">
  </div>

  <input type='submit' value="Submit" class='btn btn-default' >


  <%= link_to "Cancel", authors_path , class: "btn btn-default" %>
  <a href="<%= authors_path %>" class="btn btn-default">Cancel</a>
</form>

app/views/books/index.html.erb
<div id="book-index">
  <div class="row">
    <div class="col-md-3">
      <h3>Ruby on Rails Power</h3>
      <%= image_tag( 'covers/ruby_on_rails_power.jpg') %>
      <%= link_to "Read More", book_path(1), class: "btn btn-primary" %>
    </div>
    <div class="col-md-3">
      <h3>Ajax on Rails</h3>
      <%= image_tag( 'covers/ajax_on_rails.jpg') %>
      <%= link_to "Read More", book_path(1), class: "btn btn-primary" %>
    </div>
    <div class="col-md-3">
      <h3>Beginning PHP5</h3>
      <%= image_tag( 'covers/beginning_php_5.jpg') %>
      <%= link_to "Read More", book_path(1), class: "btn btn-primary" %>
    </div>
    <div class="col-md-3">
      <h3>Head First PHP</h3>
      <%= image_tag( 'covers/html5_trainer.jpg') %>
      <%= link_to "Read More", book_path(1), class: "btn btn-primary" %>
    </div>
  </div>
  <div class="row">
		<div class="col-md-3 col-sm-3">
			<h3>HTML5 Trainer</h3>
			<%= image_tag("covers/html5_trainer.jpg") %>
			<%=link_to "Read More", book_path(1), class:'btn btn-primary' %>
		</div>
		<div class="col-md-3 col-sm-3">
			<h3>HTML5 & CSS3</h3>
			<%= image_tag("covers/html5_css3.jpg") %>
			<%=link_to "Read More", book_path(1), class:'btn btn-primary' %>
		</div>
		<div class="col-md-3 col-sm-3">
			<h3>PHP Cookbook</h3>
			<%= image_tag("covers/php_cookbook.jpg") %>
			<%=link_to "Read More", book_path(1), class:'btn btn-primary' %>
		</div>
		<div class="col-md-3 col-sm-3">
			<h3>Ruby On Rails Tutorial</h3>
			<%= image_tag("covers/ruby_on_rails_tutorial.jpg") %>
			<%=link_to "Read More", book_path(1), class:'btn btn-primary' %>
		</div>
	</div>

</div>

app/views/books/new.html.erb
<h2>Add New Book</h2>

<%= form_for @book do |f| %>
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %><br>
  </div>

  <div class="form-group">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn, class: 'form-control' %><br>
  </div>

  <div class="form-group">
    <%= f.label :category %><br>
    <%= f.select :category_id, Category.all.collect {|x| [x.name, x.id] },
      {:include_blank => 'Select One'}, class: 'form-control' %><br><br>
  </div>

  <div class="form-group">
    <%= f.label :author %><br>
    <%= f.select :author_id, Author.all.collect{|x| [x.first_name, x.last_name]},
    {include_blank: 'Select One'}, class: 'form-control' %><br><br>
  </div>

  <div class="form-group">
    <%= f.label :author %>
    <%= f.select :author_id, Author.all.collect{|x|, [x.first_name, x.last_name]} ,
    {include_blank: 'Select One'}, class: 'form-control'%><br><br>
  </div>


  <div class="form-group">
    <%= f.label :publisher %><br>
    <%= f.select :publisher_id, Publisher.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'},
                class: 'form-control'  %><br>
  </div>

  <div class="form-group">
    <%= f.label :format %><br>
    <%= f.text_field :format, class: 'form-control' %><br>
  </div>

  <div class="form-group">
    <%= f.label :year %><br>
    <%= f.text_field :year, class: 'form-control' %><br>
  </div>

  <div class="form-group">
    <%= f.label :coverpath %><br>
    <%= f.text_field :coverpath, class: 'form-control' %><br>
  </div>

  <div class="form-group">
    <%= f.label :excerpt %><br>
    <%= f.text_area :excerpt, class: 'form-control' %><br>
  </div>

  <div class="form-group">
    <%= f.label :pages %><br>
    <%= f.number_field :pages, class: 'form-control' %><br>
  </div>

  <div class="form-group">
    <%= f.label :buy %><br>
    <%= f.text_field :buy ,class: 'form-control' %><br>
  </div>

  <%= f.submit "Submit", class: 'btn btn-primary' %>
  <%= link_to "Cancel", books_path, class: 'btn btn-default'%>

<% end %>

app/views/books/show.html.erb
<div id="books-show">
  <h2>Ruby on Rails Power</h2>
  <div class="row">
    <div class="books-show-left col-md-6">
      <%= image_tag('covers/ruby_on_rails_power.jpg') %>
    </div>
    <div class="book-show-right col-md-6">
      <h3>Book info:</h3>
      <ul>
        <li><strong>Category:</strong> Ruby On Rails</li>
  			<li><strong>Author:</strong> Aneesha Bakharia</li>
  			<li><strong>Publisher:</strong> Course Technology PTR</li>
  			<li><strong>Year:</strong> 2007</li>
  			<li><strong>ISBN:</strong> 1598632167</li>
  			<li><strong>Format:</strong> Paperback</li>
  			<li><strong>Pages:</strong> 678</li>
      </ul>
      <%= link_to "Buy For $5.47",  'http://www.ebay.com/itm/Ruby-Rails-Power-Comprehensive-Guide-Power-/221475598855?pt=US_Nonfiction_Book&hash=item3390f97207',
                  class: "btn btn-success", target: '_blank' %>
    </div>
  </div>
  <div class="clearfix"></div>
  <h4>Excerpt</h4>
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam elementum volutpat ipsum id dictum. Integer at fermentum ante. Quisque semper et nulla in condimentum. Mauris lacinia mi quis metus ornare tincidunt. Curabitur semper cursus magna, eget varius tellus viverra tincidunt. Suspendisse nisi magna, convallis et pellentesque in, efficitur ac quam. Curabitur blandit vestibulum vehicula. Fusce vitae facilisis dolor. Proin nec tristique magna, eu venenatis ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>

</div>

app/views/categories/edit.html.erb
<h2>Edit Category</h2>

<%= form_for @category do |f| %>
  <% if @category.errors.any? %>
    <% @category.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %><br>
  </div>

  <%= f.submit "Submit", class: "btn btn-primary" %>
  <%= link_to "Cancel", categories_path, class: "btn btn-default" %>

<% end %>

app/views/categories/index.html.erb
<h2>Categories</h2>

<table class='table table-striped '>
  <thead>
    <tr>
      <th>Category Name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td>
        <%= link_to "Edit", edit_category_path(category.id) %>| <%= link_to "Delete", category_path(category),method: :delete, data: { confirm: "Are you sure?" } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<h2>Add New Category</h2>

<%= form_for @category do |f| %>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  
  <%= f.submit "Submit", class: "btn btn-primary" %>
  <%= link_to "Cancel", categories_path, class: "btn btn-default" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Bookstore Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render "partials/navbar" %>
  <header>
    <div class="container">
      <h1>The BookStore <small>Welcome<small></h1>
    </div>
  </header>

  <section>
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <%= render "partials/notice_message" %>
          <%= yield %>
        </div>
        <div class="col-md-4">
          <%= render 'partials/sidebar' %>
        </div>
      </div>
    </div>
  </section>

  <footer>
    <div class="container">
      <p>Copyright &copy; 2014, All Rights Reserved</p>
    </div>
  </footer>

</body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Bookstore</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= (params[:controller] == 'books'&& params[:action]=='index') ? "active" : "" %>">
          <%= link_to "Home", root_path %>
        </li>
        <li class="<%= params[:controller] == 'about' ? "active" : "" %>">
          <%= link_to "About", about_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Add New <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Book", new_book_path %></li>
            <li><%= link_to "Category", new_category_path %></li>
            <li><%= link_to "Author", new_author_path %></li>
            <li><%= link_to "Publisher", new_publisher_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_notice_message.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>

app/views/partials/_sidebar.html.erb
<% if params[:controller] == 'about' %>
  <div class="well">
    <h4>Location Info</h3>
    <ul>
      <li>The Book Store</li>
      <li>499 Massachusetts Ave, Unit 2</li>
      <li>Boston, MA 02110</li>
      <li>Phone: (617) 555-5555</li>
      <li>Email: support@thebookstore.com</li>
    </ul>
  </div>
<% end %>

<% if params[:controller] == 'books' && params[:action] == 'index' || params[:action] == 'show' %>
  <div class="list-group">
    <a href="#" class="list-group-item">Ruby On Rails</a>
    <a href="#" class="list-group-item">PHP</a>
    <a href="#" class="list-group-item">HTML5</a>
  </div>
<% end %>

app/views/publishers/new.html.erb
<h2>Add New Publisher</h2>

<%= form_for @publisher do |f| %>
    f.lab
<% end %>